### PR TITLE
:bug: Fix some bugs regarding fuzzing

### LINKED ISSUE #28: Fix bugs regarding the fuzzing
### Expected behavior
 - Try to run the fuzzing without any errors.

### Actual behavior
 - There are some bugs with running the fuzzing

### PR DESCRIPTION
**Pull request by hrmhatef**
### What was the problem?

- This PR resolves #28 

### How was it solved?
 - Run the fuzzing the fixed the issues.

### How was it tested?
 - Fuzzing will run without any problem.

### CODE REVIEW

File: src/handle_provide_parameter.c [hunk 1]
```diff
@@ -413,21 +441,29 @@ static void handle_governor_propose(ethPluginProvideParameter_t *msg, context_t
             context->next_param = VALUE;
             break;
         case VALUE:
-            copy_parameter(context->lisk.body.governorPropose.data.second[counter].value,
-                           msg->parameter,
-                           INT256_LENGTH);
-            if (counter + 1 < context->lisk.body.governorPropose.value_len) {
-                counter++;
-                context->next_param = SECOND_VALUE;
+            if (counter < context->lisk.body.governorPropose.value_len) {
```
Comment (shuse2) [inline src/handle_provide_parameter.c]: I think it's better to make it early return for readability
```
if (counter >= context->lisk.body.governorPropose.value_len) {
  msg->result = ETH_PLUGIN_RESULT_ERROR;
  break;
}
```

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: src/handle_provide_parameter.c (hunk 1 above)
Comment (hrmhatef) [reply src/handle_provide_parameter.c]: Good point, thank you.

Done.

**Review by nagdahimanshu — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]
